#pragma once

#include "cocos2d.h"

#define TYPE_ZOMBIE 1511
#define TYPE_ZOMBIE_ATTACK 15111
#define TYPE_ZOMBIE_SKILL 15112
#define TYPE_PLAYER 1512
#define TYPE_BULLET 1513
#define TYPE_ZOMBIEBULLET 15131
#define TYPE_ARCHITECT 1514
#define TYPE_GROUND 1515
#define TYPE_FALLING_ZOMBIE 1516
#define TYPE_JUMPING_ZOMBIE 1517
#define TYPE_HUGE_ZOMBIE 1518

#define CATEGORY_ARCHITECT 1
#define CATEGORY_BULLET 1 << 1
#define CATEGORY_GROUND 1 << 2
#define CATEGORY_PLAYER 1 << 3
#define CATEGORY_ZOMBIE 1 << 4
#define CATEGORY_ZOMBIEBULLET  1 << 5
#define CATEGORY_FALLING_ZOMBIE 1 << 6	//구조물에서 떨어지는 좀비

#define ZORDER_ARCHITECT 10
#define ZORDER_ZOMBIE 11
#define ZORDER_GROUND 9
#define ZORDER_BUTTON 15
#define ZORDER_BULLET 13
#define ZORDER_DEADZOMBIE 11
#define ZORDER_DEADPLAYER 46
#define ZORDER_LEFTHAND 13
#define ZORDER_RIGHTHAND 7
#define ZORDER_PLAYER 12
#define ZORDER_INTERFACE 50
#define ZORDER_HUGEZOMBIE 45
#define ZORDER_FADE 90
#define ZORDER_BASEGROUND 7
#define ZORDER_TUTORIAL_BACK 99
#define ZORDER_TUTORIAL_MESSAGE 100

#define BASE_GROUND_HEIGHT 165

USING_NS_CC;

struct UserDataInBody
{
	cocos2d::CCSprite* mSprite;
	void* mChr;
	int mType;
};